data:
  '2015':
  - user.mromano.AllYear.physics_Main.DAOD_TOPQ1.grp15_v01_p4345.TTDIFFXS361_v01.MINI362_v1
  '2016':
  - user.mromano.AllYear.physics_Main.DAOD_TOPQ1.grp16_v01_p4345.TTDIFFXS361_v01.MINI362_v1
  '2017':
  - user.mromano.AllYear.physics_Main.DAOD_TOPQ1.grp17_v01_p4345.TTDIFFXS361_v01.MINI362_v1
  '2018':
  - user.mromano.AllYear.physics_Main.DAOD_TOPQ1.grp18_v01_p4345.TTDIFFXS361_v01.MINI362_v1
