---
# https://its.cern.ch/jira/projects/TTDIFFXS/issues/TTDIFFXS-361?filter=allopenissues
# MC weights and alternative samples
# With KLFitter

# ttbar Powheg+Pythia8 nominal
ttbar:
    mc16a: user.mromano.410470.PhPy8EG.DAOD_TOPQ1.e6337_a875_r9364_p4346.TTDIFFXS361_v08.MINI362_v1_klfitter
    mc16d: user.mromano.410470.PhPy8EG.DAOD_TOPQ1.e6337_a875_r10201_p4346.TTDIFFXS361_v08.MINI362_v1_klfitter
    mc16e: user.mromano.410470.PhPy8EG.DAOD_TOPQ1.e6337_a875_r10724_p4346.TTDIFFXS361_v08.MINI362_v1_klfitter