---
# https://its.cern.ch/jira/projects/TTDIFFXS/issues/TTDIFFXS-361?filter=allopenissues
# With SF systematics and CR loose selection
# With KLFitter

# ttbar Powheg+Pythia8 nominal
ttbar:
    mc16a: user.mromano.410470.PhPy8EG.DAOD_TOPQ1.e6337_s3126_r9364_p4346.TTDIFFXS361_v06.MINI362_v1_klfitter
    mc16d: user.mromano.410470.PhPy8EG.DAOD_TOPQ1.e6337_s3126_r10201_p4346.TTDIFFXS361_v06.MINI362_v1_klfitter
    mc16e: user.mromano.410470.PhPy8EG.DAOD_TOPQ1.e6337_s3126_r10724_p4346.TTDIFFXS361_v06.MINI362_v1_klfitter