---
subcampaign_tag:
    mc16a: r9364
    mc16d: r10201
    mc16e: r10724

# Dataset number
# https://its.cern.ch/jira/projects/TTDIFFXS/issues/TTDIFFXS-361?filter=allissues
dsid:
    # Signal

    ttbar:         # PhPy8EG (nominal) mt = 172.5 GeV, hdamp = 1.5*mt 
        - 410470
    ttbar_hw:      # PowhegHerwig7EvtGen #- PWGH7
        - 411233
        - 411234
    ttbar_amc:     # aMcAtNloPy8EvtGen #- MCatNLO
        - 410464
        - 410465
    ttbar_sh:      # Sherpa v.2.2.8
        - 700048
        - 700049
        - 700050
    ttbar_mt169:   # Same as nominal but with mt = 169 GeV
        - 411044
        - 411052
    ttbar_mt176:   # Same as nominal but with mt = 176 GeV
        - 411051
        - 411059
    ttbar_hdamp:   # same as nominal but with hdamp set to 3*mt
        - 410480
        - 410482
    ttbar_madspin: # POWHEG+Pythia8 ttbar production with MadSpin decay, Powheg hdamp equal 1.5*top mass, A14 tune
        - 601708 # dilepton
        - 601407 # single lepton
    ttbar_pthard1: # POWHEG+Pythia8 ttbar production with Powheg hdamp equal 1.5*top mass, A14 tune, pTHard=1, ME NNPDF30 NLO, A14 NNPDF23 LO from DSID 410450 LHE files with Shower Weights added
        - 601491 # dilepton
        - 601497 # one lepton
    tthar_sh2212: # Sherpa v.2.2.12 ttbar + 0,1j@NLO + 2,3,4j@LO
        - 700660 # dilepton.
        - 700661 # single lepton (minus)
        - 700662 # single lepton (plus)
    ttbar_minnlops: # MiNNLOPS
        - 950473

    # Backgrounds

    # single top
    singleTop:     # PhPy8EG
        # t-channel
        - 410658
        - 410659
        # tW
        - 410646
        - 410647
        # s-channel
        - 410644
        - 410645
    singleTop_DS:  # PhPy8EG with DS scheme
        - 410654
        - 410655
    singleTop_hw:  # PowhegHerwig7EvtGen
        # t-channel
        - 411032
        - 411033
        # tW
        - 411036
        - 411037
        # s-channel
        - 411034
        - 411035
    singleTop_amc:  # aMcAtNloPy8EG
        - 412002
        - 412003   # tW_dilepton, but 412002 is tW_inclusive?
        - 412004
        - 412005
    singleTop_tW_DR_dyn:  # POWHEG+Pythia8+EvtGen tW production, DR scheme, dynamic scale, inclusive, hdamp equal 1.5*top mass, A14 tune, ME NNPDF30 NLO, A14 NNPDF23 LO
        - 601619 # antitop
        - 601623 # top
    singleTop_tW_DR_dyn_3mthdamp:  # POWHEG+Pythia8+EvtGen tW production, DR scheme, dynamic scale, inclusive, with Powheg hdamp equal 3*top mass, A14 tune, ME NNPDF30 NLO, A14 NNPDF23 LO
        - 601618 # antitop
        - 601622 # top
    singleTop_tW_DS_dyn:  # POWHEG+Pythia8+EvtGen tW production, DR scheme, dynamic scale, inclusive, hdamp equal 1.5*top mass, A14 tune, ME NNPDF30 NLO, A14 NNPDF23 LO
        - 601627 # antitop
        - 601631 # top
    singleTop_tW_DS_dyn_3mthdamp:  # POWHEG+Pythia8+EvtGen tW production, DR scheme, dynamic scale, inclusive, with Powheg hdamp equal 3*top mass, A14 tune, ME NNPDF30 NLO, A14 NNPDF23 LO
        - 601626 # antitop
        - 601630 # top

    # W+jets
    Wjets:
        # 364156 - 364197
        !!python/object/apply:builtins.range [364156, 364198]

    # Z+jets
    Zjets:
        # 364100 - 364141
        !!python/object/apply:builtins.range [364100, 364142]

    # ttV
    ttV:           # aMcAtNloPythia8EvtGen
        - 410155   # ttW
        - 410156   # ttZ,Z->nunu
        - 410157   # ttZ,Z->qq
        - 410218   # ttee
        - 410219   # ttmumu
        - 410220   # tttautau
    # For background systematics
    ttV_syst: 
        - 410560   # MadGraph tZq
        - 410080   # MadGraph 4topSM
        - 410081   # MadGraph ttWW
        - 410408   # aMcAtNloPythia8EvtGen tWZ,Z->ll

    # Di-boson
    VV:            # Sherpa
        - 363356   # Z(qq)Z(ll)
        - 363358   # W(qq)Z(ll)
        - 363359   # W+(->qq)W-(->lv) with 0,1j@NLO + 2,3j@LO
        - 363360   # W+(->lv)W-(->qq) with 0,1j@NLO + 2,3j@LO
        - 363489   # W(lv)Z(qq)
    # For background systematics
    VV_syst:       # Sherpa
        - 364250   # llll
        - 364253   # lllnu
        - 364254   # llnunu
        - 364255   # lnununu

    # ttH
    ttH:           # PhPy8EG
        - 346344   # ttH, mH=125, semilep